### ISSUE TITLE
User Data does not execute when using the library

### ISSUE THREAD

**Issue by fredski-github** [udondan/cdk-ec2-key-pair#40] opened 2022-01-27 20:27 UTC
- SSH key pair is created and works
- User Data is uploaded to the EC2 Instance
- User Data does not execute

**Comment by phelewski** [comment] 2022-01-27 20:43
Here is some sample code to reproduce this issue.

cdk example:
``` python
        # Create the Key Pair
        ec2_ssh_key = KeyPair(
            self,
            "A-Key-Pair",
            name="foobar-ec2-key",
            description="This is a Key Pair for the EC2 Instance",
            store_public_key=True,
        )

        iam_user = aws_iam.User.from_user_name(
            self, id="IAMUser", user_name="foobar"
        )
        # Grant read access to the private key to a role or user
        ec2_ssh_key.grant_read_on_private_key(iam_user)

        # Grant read access to the public key to another role or user
        ec2_ssh_key.grant_read_on_public_key(iam_user)

        with open("userdata.txt") as f:
            user_data = f.read()

        ec2_instance = aws_ec2.Instance(
            self,
            "Foobar",
            ...
        )
        ec2_instance.add_user_data(user_data)
```

userdata.txt
```
echo "Hello World!"
```

**Comment by udondan** [comment] 2022-01-28 10:01
I just tested this and it perfectly worked.

From a logical perspective, it's unlikely this is related. The EC2 instance doesn't care nor does it know how the key has been generated. The key itself is an AWS resource and all the EC2 instance gets when it is started is a reference to the key. You've already confirmed the key is valid. So I don't see how this could be related to this library.

**Comment by phelewski** [comment] 2022-01-28 13:56
Thanks for checking on this. You're correct the key is created and linked properly to the EC2 Instance. For some reason when I'm running an more complex user data script which is downloading items via `curl`, those steps are broken on the instance creation. It may be a weird timeout issue or competing commands with yum updating packages at the same time during the instance creation. I'm able to get my custom user data script to work with some added wait/sleep statements.

It is weird however that I can't reproduce the same installation error when I'm pointing to an already existing KeyPair, I don't need those wait/sleep statements.

**Comment by fredski-github** [comment] 2022-01-28 20:47
The custom resource might be causing a racing condition at the OS level with cloud-init. We are using CDK v2, we have not tried with v1.

**Comment by udondan** [comment] 2022-01-29 08:00
No, it does not. It can not.

The key pair is a CFN dependency of your instances. You should see this in you CDK output and the CloudFormation events. First the KeyPair is created, then the instance.

The custom resource is a lambda function that is already done before CloudFormation sends the call to create the instance.

When your instance is created, there is absolutely nothing from this package that's left running.

At the time the instance is created, the KeyPair exists and is no different than any other pre-existing KeyPair. It *is* a pre-existing KeyPair.

You can also see all the stuff happening in the SystemLog in the EC2 console. What you should see there is the key is added before your userdata is executed. Not at the same time. But even if that's not the case, it is technically impossible that it is related to this lib.

**Comment by udondan** [comment] 2022-02-14 07:31
Going to close this, as there is no logical explanation how this package is related to the described problems. It's more likely there's a general timing issue with your userdata. 

Feel free to reopen with a reproducible example project.

**Closed by udondan** 2022-02-14 07:31 UTC
